// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQa8YKMASllC1cpas_dwIrCFzQFryyOy4',
    appId: '1:344038424936:web:494b21ca34f65f01f596dd',
    messagingSenderId: '344038424936',
    projectId: 'women-safety-app-57eab',
    authDomain: 'women-safety-app-57eab.firebaseapp.com',
    storageBucket: 'women-safety-app-57eab.appspot.com',
    measurementId: 'G-VYM79V8472',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRZ_ZZkUVw8PJjzQ_AzYQSv0FxigcqE9w',
    appId: '1:344038424936:android:f5b827ba055a3d08f596dd',
    messagingSenderId: '344038424936',
    projectId: 'women-safety-app-57eab',
    storageBucket: 'women-safety-app-57eab.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4N82tAzAue6LiP4mgQXZTe7QvLIkmPeM',
    appId: '1:344038424936:ios:9faac4cdce2e5004f596dd',
    messagingSenderId: '344038424936',
    projectId: 'women-safety-app-57eab',
    storageBucket: 'women-safety-app-57eab.appspot.com',
    iosClientId: '344038424936-tiel3a0rad64i51opehoufa3pua5c9m1.apps.googleusercontent.com',
    iosBundleId: 'com.example.womenSafetyApp',
  );
}
